<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chess.Application\Chess.Application.csproj" />
    <ProjectReference Include="..\Chess.Domain\Chess.Domain.csproj" />
    <ProjectReference Include="..\Chess.Engine\Chess.Engine.csproj" />
    <ProjectReference Include="..\Chess.UI.CLI\Chess.UI.CLI.csproj" />
  </ItemGroup>

</Project>
